# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/383ac71a-0b70-43fc-bdd1-8f8d6ff30120";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3E15-909D";
    fsType = "vfat";
  };

  swapDevices = [];

  fileSystems."/home/koss/mount/ssd" = {
    device = "/dev/disk/by-uuid/671dc1b7-2f8d-4e59-b65f-ee44bcf949ba";
    fsType = "ext4";
    options = [
      "defaults,discard"
    ];
  };

  fileSystems."/home/koss/mount/hdd" = {
    device = "/dev/disk/by-uuid/4f93c780-725e-46b9-bea8-d59b52ecac35";
    fsType = "ext4";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
